In [11]:
from SPARQLWrapper import SPARQLWrapper, JSON
import pandas as pd
endpoint_url = "https://query.wikidata.org/sparql"
query = """
SELECT ?park ?parkLabel ?country ?countryLabel ?countryCode ?area ?coordinate ?inception WHERE {
  ?park wdt:P31 wd:Q46169;           # Instance of national park
        wdt:P17 ?country;            # Located in country
        wdt:P2046 ?area;             # Area of the park
        wdt:P625 ?coordinate;
        wdt:P571 ?inception.
  ?country wdt:P30 wd:Q15;           # Country is in Africa
           wdt:P298 ?countryCode.    # ISO 3166-1 alpha-3 code

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
"""
sparql = SPARQLWrapper(endpoint_url)
sparql.setQuery(query)
sparql.setReturnFormat(JSON)
results = sparql.query().convert()
# Convert the results into a Pandas dataframe.
cols = results['head']['vars']
out = []
for row in results['results']['bindings']:
    item = []
    for c in cols:
        item.append(row.get(c, {}).get('value'))
    out.append(item)

df = pd.DataFrame(out, columns=cols)
df.head()

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)>

In [2]:
from SPARQLWrapper import SPARQLWrapper, JSON
import pandas as pd
endpoint_url = "https://query.wikidata.org/sparql"
query = """
SELECT ?country ?countryLabel ?currency ?currencyLabel ?region ?regionLabel ?officialLanguage ?officialLanguageLabel ?capital ?capitalLabel ?emoji ?iso3 ?population WHERE {
  ?country wdt:P31 wd:Q6256;           # Instance of country
           wdt:P30 wd:Q15.             # In the continent of Africa

  OPTIONAL { ?country wdt:P38 ?currency. }          # Currency
  OPTIONAL { ?country wdt:P361 ?region. }           # Part of (region)
  OPTIONAL { ?country wdt:P37 ?officialLanguage. }  # Official language
  OPTIONAL { ?country wdt:P36 ?capital. }           # Capital
  OPTIONAL { ?country wdt:P1813 ?shortName. }       # Short name
  OPTIONAL { ?country wdt:P487 ?emoji. }            # Emoji regional indicator sequence
  OPTIONAL { ?country wdt:P298 ?iso3. }            # Emoji regional indicator sequence
  OPTIONAL { ?country wdt:P1082 ?population. }            # Emoji regional indicator sequence

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}

"""
sparql = SPARQLWrapper(endpoint_url)
sparql.setQuery(query)
sparql.setReturnFormat(JSON)
sparql.addCustomHttpHeader("User-Agent", "WAAgent")  # Add a user agent

results = sparql.query().convert()
# Convert the results into a Pandas dataframe.
cols = results['head']['vars']
out = []
for row in results['results']['bindings']:
    item = []
    for c in cols:
        item.append(row.get(c, {}).get('value'))
    out.append(item)

df_country_information = pd.DataFrame(out, columns=cols)
df_country_information.head()

,country,countryLabel,currency,currencyLabel,region,regionLabel,officialLanguage,officialLanguageLabel,capital,capitalLabel,emoji,iso3,population
0,http://www.wikidata.org/entity/Q79,Egypt,http://www.wikidata.org/entity/Q199462,Egyptian pound,http://www.wikidata.org/entity/Q7204,Middle East,http://www.wikidata.org/entity/Q13955,Arabic,http://www.wikidata.org/entity/Q85,Cairo,🇪🇬,EGY,94798827
1,http://www.wikidata.org/entity/Q79,Egypt,http://www.wikidata.org/entity/Q199462,Egyptian pound,http://www.wikidata.org/entity/Q27293,West Asia,http://www.wikidata.org/entity/Q13955,Arabic,http://www.wikidata.org/entity/Q85,Cairo,🇪🇬,EGY,94798827
2,http://www.wikidata.org/entity/Q79,Egypt,http://www.wikidata.org/entity/Q199462,Egyptian pound,http://www.wikidata.org/entity/Q27381,North Africa,http://www.wikidata.org/entity/Q13955,Arabic,http://www.wikidata.org/entity/Q85,Cairo,🇪🇬,EGY,94798827
3,http://www.wikidata.org/entity/Q114,Kenya,http://www.wikidata.org/entity/Q202882,Kenyan shilling,http://www.wikidata.org/entity/Q27407,East Africa,http://www.wikidata.org/entity/Q1860,English,http://www.wikidata.org/entity/Q3870,Nairobi,🇰🇪,KEN,48468138
4,http://www.wikidata.org/entity/Q114,Kenya,http://www.wikidata.org/entity/Q202882,Kenyan shilling,http://www.wikidata.org/entity/Q27407,East Africa,http://www.wikidata.org/entity/Q7838,Swahili,http://www.wikidata.org/entity/Q3870,Nairobi,🇰🇪,KEN,48468138

In [3]:
df_country_information = df_country_information[df_country_information['regionLabel'].str.contains('Africa', case=False, na=False)]

In [6]:
query = """
SELECT ?park ?parkLabel ?country ?countryLabel ?countryCode ?area ?coordinate  ?inception WHERE {
  ?park wdt:P31 wd:Q473972;           # Instance of protected area
        wdt:P17 ?country;            # Located in country
        wdt:P2046 ?area;             # Area of the park
        wdt:P625 ?coordinate;
        wdt:P571 ?inception.
  ?country wdt:P30 wd:Q15;           # Country is in Africa
           wdt:P298 ?countryCode.    # ISO 3166-1 alpha-3 code

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}

"""
sparql = SPARQLWrapper(endpoint_url)
sparql.setQuery(query)
sparql.setReturnFormat(JSON)
sparql.addCustomHttpHeader("User-Agent", "WAAgent")  # Add a user agent

results = sparql.query().convert()
# Convert the results into a Pandas dataframe.
cols = results['head']['vars']
out = []
for row in results['results']['bindings']:
    item = []
    for c in cols:
        item.append(row.get(c, {}).get('value'))
    out.append(item)

df_protected = pd.DataFrame(out, columns=cols)
df_protected.head()

,park,parkLabel,country,countryLabel,countryCode,area,coordinate,inception
0,http://www.wikidata.org/entity/Q310719,iSimangaliso Wetland Park,http://www.wikidata.org/entity/Q258,South Africa,ZAF,1328901,Point(32.5 -28.0),2000-11-01T00:00:00Z
1,http://www.wikidata.org/entity/Q310719,iSimangaliso Wetland Park,http://www.wikidata.org/entity/Q258,South Africa,ZAF,1328901,Point(32.55 -27.8389),2000-11-01T00:00:00Z
2,http://www.wikidata.org/entity/Q184284,Cederberg,http://www.wikidata.org/entity/Q258,South Africa,ZAF,710,Point(19.0833 -32.3333),1973-01-01T00:00:00Z
3,http://www.wikidata.org/entity/Q1180030,De Hoop Nature Reserve,http://www.wikidata.org/entity/Q258,South Africa,ZAF,34000,Point(20.5478 -34.4342),1957-01-01T00:00:00Z
4,http://www.wikidata.org/entity/Q2562112,Baviaanskloof Mega Reserve,http://www.wikidata.org/entity/Q258,South Africa,ZAF,500000,Point(24.1333 -33.5),1920-01-01T00:00:00Z

In [7]:
query = """
SELECT ?park ?parkLabel ?country ?countryLabel ?countryCode ?capacity ?coordinate ?inception WHERE {
  ?park wdt:P31 wd:Q483110;           # Instance of stadium
        wdt:P17 ?country;            # Located in country
        wdt:P1083 ?capacity;         # Maximum capacity
        wdt:P625 ?coordinate;
        wdt:P571 ?inception.
  ?country wdt:P30 wd:Q15;           # Country is in Africa
           wdt:P298 ?countryCode.    # ISO 3166-1 alpha-3 code

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}

"""
sparql = SPARQLWrapper(endpoint_url)
sparql.setQuery(query)
sparql.setReturnFormat(JSON)
sparql.addCustomHttpHeader("User-Agent", "WAAgent")  # Add a user agent

results = sparql.query().convert()
# Convert the results into a Pandas dataframe.
cols = results['head']['vars']
out = []
for row in results['results']['bindings']:
    item = []
    for c in cols:
        item.append(row.get(c, {}).get('value'))
    out.append(item)

df_stadium = pd.DataFrame(out, columns=cols)
df_stadium.head()

,park,parkLabel,country,countryLabel,countryCode,capacity,coordinate,inception
0,http://www.wikidata.org/entity/Q187042,Peter Mokaba Stadium,http://www.wikidata.org/entity/Q258,South Africa,ZAF,41733,Point(29.468765 -23.924689),2010-01-01T00:00:00Z
1,http://www.wikidata.org/entity/Q189337,Royal Bafokeng Stadium,http://www.wikidata.org/entity/Q258,South Africa,ZAF,42000,Point(27.160833333 -25.578611111),1999-01-01T00:00:00Z
2,http://www.wikidata.org/entity/Q3496077,Stade du 26 Mars,http://www.wikidata.org/entity/Q912,Mali,MLI,50000,Point(-7.921667 12.604444),2001-12-31T00:00:00Z
3,http://www.wikidata.org/entity/Q840778,Suez Stadium,http://www.wikidata.org/entity/Q79,Egypt,EGY,25000,Point(32.5425 29.9575),1990-01-01T00:00:00Z
4,http://www.wikidata.org/entity/Q598736,Johannesburg Stadium,http://www.wikidata.org/entity/Q258,South Africa,ZAF,37500,Point(28.062513888 -26.193822222),1992-01-01T00:00:00Z

In [8]:
query = """
SELECT ?park ?parkLabel ?country ?countryLabel ?countryCode ?coordinate ?inception WHERE {
  ?park wdt:P31 wd:Q24398318;           # Instance of religious building
        wdt:P17 ?country.           # Located in country
  ?country wdt:P30 wd:Q15;           # Country is in Africa
           wdt:P298 ?countryCode;    # ISO 3166-1 alpha-3 code
           wdt:P625 ?coordinate;
           wdt:P571 ?inception.

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}

"""
sparql = SPARQLWrapper(endpoint_url)
sparql.setQuery(query)
sparql.setReturnFormat(JSON)
sparql.addCustomHttpHeader("User-Agent", "WAAgent")  # Add a user agent

results = sparql.query().convert()
# Convert the results into a Pandas dataframe.
cols = results['head']['vars']
out = []
for row in results['results']['bindings']:
    item = []
    for c in cols:
        item.append(row.get(c, {}).get('value'))
    out.append(item)

df_religious = pd.DataFrame(out, columns=cols)
df_religious.head()

,park,parkLabel,country,countryLabel,countryCode,coordinate,inception
0,http://www.wikidata.org/entity/Q61685729,Al Abu Stit mosque,http://www.wikidata.org/entity/Q79,Egypt,EGY,Point(29.0 27.0),1922-02-28T00:00:00Z
1,http://www.wikidata.org/entity/Q124822454,Limestone Chapel of Hatshepsut in Karnak,http://www.wikidata.org/entity/Q79,Egypt,EGY,Point(29.0 27.0),1922-02-28T00:00:00Z
2,http://www.wikidata.org/entity/Q124831396,Alabaster Chapel of Amenhotep I,http://www.wikidata.org/entity/Q79,Egypt,EGY,Point(29.0 27.0),1922-02-28T00:00:00Z
3,http://www.wikidata.org/entity/Q124832708,Alabaster Chapel of Amenhotep II,http://www.wikidata.org/entity/Q79,Egypt,EGY,Point(29.0 27.0),1922-02-28T00:00:00Z
4,http://www.wikidata.org/entity/Q124884277,Alabaster Chapel of Thutmosis IV,http://www.wikidata.org/entity/Q79,Egypt,EGY,Point(29.0 27.0),1922-02-28T00:00:00Z

In [9]:
import os
print(os.getcwd())

/Users/dhruvpandit/Documents/GitHub/with-sandbox/notebooks/dataset_setup/country_profiles

In [9]:
un = pd.read_excel(r'../../../datasets/general/whc-sites-2024.xls')
count = pd.read_excel(r'../../../datasets/unwto/countryContUNWTO.xlsx')
un = un[['region_en', 'states_name_en', 'category', 'category_short', 'name_en', 'short_description_en','longitude'	,'latitude',	'area_hectares']]
un = un[un['states_name_en'].isin(count['country'].unique())]
un = un.merge(count, left_on='states_name_en', right_on='country', )
un = un[['category' ,'category_short', 'country', 'iso3_code', 'sub_region', 'name_en', 'short_description_en','longitude'	,'latitude',	'area_hectares']]
#un = un[un['region_en'] == 'Africa']

In [10]:
un

,category,category_short,country,iso3_code,sub_region,name_en,short_description_en,longitude,latitude,area_hectares
0,Cultural,C,Algeria,DZA,Northern Africa,Al Qal'a of Beni Hammad,<p>In a mountainous site of extraordinary beau...,4.786840,35.818440,150.00
1,Mixed,C/N,Algeria,DZA,Northern Africa,Tassili n'Ajjer,<p>Located in a strange lunar landscape of gre...,9.000000,25.500000,7200000.00
2,Cultural,C,Algeria,DZA,Northern Africa,M'Zab Valley,"<p>A traditional human habitat, created in the...",3.683330,32.483330,665.03
3,Cultural,C,Algeria,DZA,Northern Africa,Djémila,"<p>Situated 900 m above sea-level, Dj&eacute;m...",5.736670,36.320560,30.60
4,Cultural,C,Algeria,DZA,Northern Africa,Tipasa,"<p>On the shores of the Mediterranean, Tipasa ...",2.383333,36.550000,52.16
...,...,...,...,...,...,...,...,...,...,...
121,Cultural,C,Uganda,UGA,Eastern Africa,Tombs of Buganda Kings at Kasubi,<p>The Tombs of Buganda Kings at Kasubi consti...,32.551389,0.348611,26.80
122,Natural,N,Zimbabwe,ZWE,Eastern Africa,"Mana Pools National Park, Sapi and Chewore Saf...","<p>On the banks of the Zambezi, great cliffs o...",29.408056,-15.819444,676600.00
123,Cultural,C,Zimbabwe,ZWE,Eastern Africa,Matobo Hills,<p>The area exhibits a profusion of distinctiv...,28.500000,-20.500000,205000.00
124,Cultural,C,Zimbabwe,ZWE,Eastern Africa,Great Zimbabwe National Monument,<p>The ruins of Great Zimbabwe &ndash; the cap...,30.933333,-20.283333,722.00
125,Cultural,C,Zimbabwe,ZWE,Eastern Africa,Khami Ruins National Monument,"<p>Khami, which developed after the capital of...",28.376667,-20.158333,0.00

In [14]:
import os
os.getcwd()

'/Users/dhruvnovaims/Library/Mobile Documents/com~apple~CloudDocs/Documents/GitHub/with-sandbox/notebooks/dataset_setup/country_profiles'

In [15]:
un.to_excel(r'../../../datasets/new_platform/country_profiles/un_sites_2024.xlsx',sheet_name='UN Sites')

In [11]:
with pd.ExcelWriter('../../../datasets/dashboards/country_cultural.xlsx') as writer:
    df.to_excel(writer, sheet_name='National Parks')
    df_stadium.to_excel(writer, sheet_name='Sports Stadiums')
    df_protected.to_excel(writer, sheet_name='Protected Areas')
    df_religious.to_excel(writer, sheet_name='Religious Sites')
    un.to_excel(writer, sheet_name='UN Sites')
    df_country_information.to_excel(writer, sheet_name='Country Information')

In [2]:
from SPARQLWrapper import SPARQLWrapper, JSON
import pandas as pd
endpoint_url = "https://query.wikidata.org/sparql"
query = """
SELECT ?airport ?airportLabel ?country ?countryLabel ?countryCode WHERE {
  ?airport wdt:P31 wd:Q644371;           # Instance of national park
        wdt:P17 ?country.          # Located in country
  ?country wdt:P30 wd:Q15;           # Country is in Africa
           wdt:P298 ?countryCode.    # ISO 3166-1 alpha-3 code

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
"""
sparql = SPARQLWrapper(endpoint_url)
sparql.setQuery(query)
sparql.setReturnFormat(JSON)
sparql.addCustomHttpHeader("User-Agent", "WAAgent")  # Add a user agent

results = sparql.query().convert()
# Convert the results into a Pandas dataframe.
cols = results['head']['vars']
out = []
for row in results['results']['bindings']:
    item = []
    for c in cols:
        item.append(row.get(c, {}).get('value'))
    out.append(item)

df_airport = pd.DataFrame(out, columns=cols)
df_airport.head()

,airport,airportLabel,country,countryLabel,countryCode
0,http://www.wikidata.org/entity/Q269633,El Nouzha Airport,http://www.wikidata.org/entity/Q79,Egypt,EGY
1,http://www.wikidata.org/entity/Q326268,Sharm el-Sheikh International Airport,http://www.wikidata.org/entity/Q79,Egypt,EGY
2,http://www.wikidata.org/entity/Q385191,Hurghada International Airport,http://www.wikidata.org/entity/Q79,Egypt,EGY
3,http://www.wikidata.org/entity/Q461793,Cairo International Airport,http://www.wikidata.org/entity/Q79,Egypt,EGY
4,http://www.wikidata.org/entity/Q123222,Marsa Alam International Airport,http://www.wikidata.org/entity/Q79,Egypt,EGY

In [3]:
endpoint_url = "https://query.wikidata.org/sparql"
query = """
SELECT ?port ?portLabel ?country ?countryLabel ?countryCode WHERE {
  ?port wdt:P31 wd:Q44782;           # Instance of national park
        wdt:P17 ?country.          # Located in country
  ?country wdt:P30 wd:Q15;           # Country is in Africa
           wdt:P298 ?countryCode.    # ISO 3166-1 alpha-3 code

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
"""
sparql = SPARQLWrapper(endpoint_url)
sparql.setQuery(query)
sparql.setReturnFormat(JSON)
sparql.addCustomHttpHeader("User-Agent", "WAAgent")  # Add a user agent

results = sparql.query().convert()
# Convert the results into a Pandas dataframe.
cols = results['head']['vars']
out = []
for row in results['results']['bindings']:
    item = []
    for c in cols:
        item.append(row.get(c, {}).get('value'))
    out.append(item)

df_port = pd.DataFrame(out, columns=cols)
df_port.head()

,port,portLabel,country,countryLabel,countryCode
0,http://www.wikidata.org/entity/Q1344739,Alexandria Port,http://www.wikidata.org/entity/Q79,Egypt,EGY
1,http://www.wikidata.org/entity/Q819050,Berenice Troglodytica,http://www.wikidata.org/entity/Q79,Egypt,EGY
2,http://www.wikidata.org/entity/Q691664,Richards Bay Coal Terminal,http://www.wikidata.org/entity/Q258,South Africa,ZAF
3,http://www.wikidata.org/entity/Q3775676,Clysma,http://www.wikidata.org/entity/Q79,Egypt,EGY
4,http://www.wikidata.org/entity/Q5212542,Damietta Port,http://www.wikidata.org/entity/Q79,Egypt,EGY

In [4]:
endpoint_url = "https://query.wikidata.org/sparql"
query = """
SELECT ?station ?stationLabel ?country ?countryLabel ?countryCode WHERE {
  ?station wdt:P31 wd:Q55488;           # Instance of national park
        wdt:P17 ?country.          # Located in country
  ?country wdt:P30 wd:Q15;           # Country is in Africa
           wdt:P298 ?countryCode.    # ISO 3166-1 alpha-3 code

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
"""
sparql = SPARQLWrapper(endpoint_url)
sparql.setQuery(query)
sparql.setReturnFormat(JSON)
sparql.addCustomHttpHeader("User-Agent", "WAAgent")  # Add a user agent

results = sparql.query().convert()
# Convert the results into a Pandas dataframe.
cols = results['head']['vars']
out = []
for row in results['results']['bindings']:
    item = []
    for c in cols:
        item.append(row.get(c, {}).get('value'))
    out.append(item)

df_station = pd.DataFrame(out, columns=cols)
df_station.head()

,station,stationLabel,country,countryLabel,countryCode
0,http://www.wikidata.org/entity/Q249897,Sidi Gaber railway station,http://www.wikidata.org/entity/Q79,Egypt,EGY
1,http://www.wikidata.org/entity/Q958574,Alexandria railway station,http://www.wikidata.org/entity/Q79,Egypt,EGY
2,http://www.wikidata.org/entity/Q821750,OR Tambo International Airport,http://www.wikidata.org/entity/Q258,South Africa,ZAF
3,http://www.wikidata.org/entity/Q1034496,Cape Town railway station,http://www.wikidata.org/entity/Q258,South Africa,ZAF
4,http://www.wikidata.org/entity/Q3095680,Aswan railway station,http://www.wikidata.org/entity/Q79,Egypt,EGY

In [5]:
endpoint_url = "https://query.wikidata.org/sparql"
query = """
SELECT ?airline ?airlineLabel ?country ?countryLabel ?countryCode WHERE {
  ?airline wdt:P31 wd:Q46970;           # Instance of national park
        wdt:P17 ?country.          # Located in country
  ?country wdt:P30 wd:Q15;           # Country is in Africa
           wdt:P298 ?countryCode.    # ISO 3166-1 alpha-3 code

  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
"""
sparql = SPARQLWrapper(endpoint_url)
sparql.setQuery(query)
sparql.setReturnFormat(JSON)
sparql.addCustomHttpHeader("User-Agent", "WAAgent")  # Add a user agent

results = sparql.query().convert()
# Convert the results into a Pandas dataframe.
cols = results['head']['vars']
out = []
for row in results['results']['bindings']:
    item = []
    for c in cols:
        item.append(row.get(c, {}).get('value'))
    out.append(item)

df_airline = pd.DataFrame(out, columns=cols)
df_airline.head()

,airline,airlineLabel,country,countryLabel,countryCode
0,http://www.wikidata.org/entity/Q169443,Civair,http://www.wikidata.org/entity/Q258,South Africa,ZAF
1,http://www.wikidata.org/entity/Q407498,Air Mali,http://www.wikidata.org/entity/Q912,Mali,MLI
2,http://www.wikidata.org/entity/Q595057,Mali Air Transport,http://www.wikidata.org/entity/Q912,Mali,MLI
3,http://www.wikidata.org/entity/Q116595,Mango,http://www.wikidata.org/entity/Q258,South Africa,ZAF
4,http://www.wikidata.org/entity/Q1340479,Air Sinai,http://www.wikidata.org/entity/Q79,Egypt,EGY

In [9]:
with pd.ExcelWriter('../../datasets/dashboards/country_profiles/transport_infra.xlsx') as writer:
    df_airport.to_excel(writer, sheet_name='Airports')
    df_airline.to_excel(writer, sheet_name='Airlines')
    df_port.to_excel(writer, sheet_name='Ports')
    df_station.to_excel(writer, sheet_name='Railway Stations')